# ===========================================
# Site Information Settings
# ===========================================

#language
language: zh-cn

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: false

# ===========================================
# Menu Settings
# ===========================================
menu:
  主页: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about

# site search option
search: false

# reward
reward:
  enable: true
  qrCode: 
    wechat: image/reward/wechat.jpg
    alipay: image/reward/alipay.jpg

# Fancybox
fancybox: true

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default

# ===========================================
# Social links Settings
# ===========================================
social:
  email: mailto:iceanness@gmail.com
  stack-overflow:
  twitter: https://twitter.com/Iceanian
  facebook:
  github: https://github.com/icean 
  weibo: http://weibo.com/1509230644
  zhihu: 

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: 20fc723d508ae536a84f44656263a202
# Google Analytics
google_analytics: UA-91888314-1

# Duoshuo
duoshuo_shortname: kompass
# Disqus
disqus_shortname: 




# ===========================================
# Version
# ===========================================
version: 2.1.x